[package]
name = "nmstatectl"
version = "0.1.0"
authors = ["Gris Ge <fge@redhat.com>"]
edition = "2018"

[[bin]]
name = "nmstatectl"
path = "nmstatectl.rs"

[dependencies]
nmstate = {path = "../lib"}
serde_yaml = "0.8"
clap = "2.33"
serde = { version = "1.0", features = ["derive"] }
